name: "publish"
on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: yarn install --frozen-lockfile
    - run: yarn test

# test action works running from the graph
test:
    runs-on: ubuntu-latest
    steps:
        -   uses: actions/checkout@v1
        -   uses: ./
            with:
                milliseconds: 1000
