name: Publish
on:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

  package:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Package
        run: npm run package
      - name: Test
        run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
