name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # check out the latest source
      - uses: actions/checkout@master

      # use cached node_modules where possible
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      # when node_modules wasn't cached, run install now
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      # build/package the app
      - name: Package
        run: npm run package

      # test the app
      - name: Test
        run: npm test

      # publish the app to npm
      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
